// we cant send big video/ voice  through this it overloads - ROUTIN MEDIA IS EXPENSIVE

// WEBRTC - VIDEO/BIG DATA

//PEER TO PEER - SIGNALING

// WEB SOCKETS CONNECTS -> NETWORK MATCHES -> SWITCH TO P2P WEBRTC

// WEBSOCKETS -> SIGNALING/CHAT/JOIN EVENTS
// WEBRTC -> AUDIO VIDEO STREAMING

// WEBTRANSPOT -> EXTREEME FPS / LIVE MEDIA/ COMPETITIVE STRAM
// SSE SERVER SENT EVENTS -> ONE WAY SERVER UPDATES